Board Cutting
Nivedita967/Data-Structure-and-Algorithms pull request #859
Opened 2021-03-19 16:59 UTC by Amit366

## Related Issue
Closes: #807 

### Describe the changes you've made
Algorithm for board cutting hackerrank problem

### Language used for coding
Java

2021-03-21 15:25 UTC, Nivedita967 requested changes
Hey @Amit366 Problem name is "Cutting Boards" so your folder name should be same.

2021-03-23 05:13 UTC, Nivedita967 commented
@Amit366 exact problem name on the hackerrank is "Cutting Boards". 
So change your folder name from `Cutting Board` to `Cutting Boards`

2021-03-23 06:18 UTC, Amit366 commented
@Nivedita967 Renamed

2021-03-24 15:48 UTC, Nivedita967 approved these changes

2021-03-24 15:49 UTC, merged